services:
  api:
    build: .
    ports:
      - "${APP_PORT:-3004}:3000"
    environment:
      - PORT=3000
      - DISABLE_FORCE_SSL=1
      - DATABASE_URL=postgres://rinha:rinha@db:5432/rinha?sslmode=disable
      # For real production, set SECRET_KEY_BASE via env (e.g. from secrets). This is for local/Docker.
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-4H7gRC0VGf6tXOay9eVysWPOnO6TIOlrC4foNzmWqnqUkIcyHJfAqRYFec+5wMYl4Z/HiRx57dN54suFXgvRCXu9S5ATeyh51LXlDiFcl4LSADBbjYejFUMSEh1j12ubUTvcA2bExZ2lv96H8yUt16XPeiVPJT7UEdte83xi9eBcYTw/VbW/8C8EarshWd/Ra5VoHKCMihRMXwVYeV+/EI5/0f6GM4uDZTpqXu1CZq16XxyWftnGB6wjnNJQVLWVLSo+2nfYiJC3HaVFQQ6bVHVl8ihuiyMvmxXQJ2xy3Rqx1MH9ENTw6+Oif0vSzRrFQcRAAdF7HKJOl0Av46F4ocRRX5RY/re8Bt69syt6IrNzwF1eU1CbvXCnVt7K9kRqsUlDZfsy2QPRTHR3HQW+RLSaeHcT--qPeZTB91ubmpeg9d--Z8T3EVsFgzihJvL3b8R90g==}
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "3GB"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinha
    volumes:
      - ../../init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha"]
      interval: 2s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"
